<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5ef9cb5ee8172',
	'title' => 'Collection Themes',
	'fields' => array(
		array(
			'key' => 'field_5ef9cb6e4c4c9',
			'label' => 'Featured Image',
			'name' => 'featured_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'translations' => 'sync',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'collection_themes',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5efa177022ebd',
	'title' => 'Exhibition Details',
	'fields' => array(
		array(
			'key' => 'field_5efa17c02119d',
			'label' => 'Start Date',
			'name' => 'start_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
			'translations' => 'sync',
		),
		array(
			'key' => 'field_5efa17fa2119e',
			'label' => 'End Date',
			'name' => 'end_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
			'translations' => 'sync',
		),
		array(
			'key' => 'field_5efa18842119f',
			'label' => 'Location',
			'name' => 'location',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'ams' => 'Amsterdam',
				'bcn' => 'Barcelona',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'translations' => 'sync',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5efa189f211a0',
			'label' => 'Opening hours',
			'name' => 'opening_hours_toggle',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'different' => 'Exhibition hours are different from normal opening hours',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'translations' => 'sync',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5efa1941211a1',
			'label' => 'Exhibition specific opening hours',
			'name' => 'exhibition_specific_opening_hours',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5efa189f211a0',
						'operator' => '==',
						'value' => 'different',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Monday - Friday : 10:00 - 22:00
Saturday & Sunday : 10:00 - 20:00',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'br',
			'translations' => 'copy_once',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'newsexhibitions',
			),
			array(
				'param' => 'post_taxonomy',
				'operator' => '==',
				'value' => 'news_exhibitions:exhibitions',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5ef759a558571',
	'title' => 'Hero Block',
	'fields' => array(
		array(
			'key' => 'field_5efa0fd248b46',
			'label' => 'Hero Type',
			'name' => 'hero_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'normal' => 'Normal Hero',
				'collection_item' => 'Collection Item Hero',
				'exhibition' => 'Exhibition Hero',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'normal',
			'layout' => 'vertical',
			'return_format' => 'value',
			'translations' => 'sync',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5ef766fca8abb',
			'label' => 'Image Position',
			'name' => 'image_position',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'left' => 'Image Left',
				'right' => 'Image Right',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'right',
			'layout' => 'vertical',
			'return_format' => 'value',
			'translations' => 'sync',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5ef759b654ae8',
			'label' => 'Subheader',
			'name' => 'subheader',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5efa0fd248b46',
						'operator' => '==',
						'value' => 'normal',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'translations' => 'translate',
		),
		array(
			'key' => 'field_5ef759ce54ae9',
			'label' => 'Description',
			'name' => 'description',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
			'translations' => 'translate',
		),
		array(
			'key' => 'field_5ef759e954aea',
			'label' => 'image',
			'name' => 'image',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'insert' => 'append',
			'library' => 'all',
			'min' => '',
			'max' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'translations' => 'sync',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/hero',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5ef9df5645e75',
	'title' => 'Promo Block',
	'fields' => array(
		array(
			'key' => 'field_5ef9df69feacc',
			'label' => 'Header',
			'name' => 'header',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'translations' => 'translate',
		),
		array(
			'key' => 'field_5ef9df56685d6',
			'label' => 'Subheader',
			'name' => 'subheader',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'translations' => 'translate',
		),
		array(
			'key' => 'field_5ef9df56689d1',
			'label' => 'Description',
			'name' => 'description',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
			'delay' => 0,
			'translations' => 'translate',
		),
		array(
			'key' => 'field_5ef9df5668dc1',
			'label' => 'Image Position',
			'name' => 'image_position',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'left' => 'Image Left',
				'right' => 'Image Right',
			),
			'default_value' => 'right',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'translations' => 'sync',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5ef9df5669181',
			'label' => 'image',
			'name' => 'image',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'insert' => 'append',
			'library' => 'all',
			'min' => '',
			'max' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'translations' => 'sync',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/promo',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5ef99c7e484e7',
	'title' => 'Related Posts',
	'fields' => array(
		array(
			'key' => 'field_5ef9cae1eca4c',
			'label' => 'Header',
			'name' => 'header',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'translations' => 'translate',
		),
		array(
			'key' => 'field_5ef9caf7eca4d',
			'label' => 'Description',
			'name' => 'description',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'translations' => 'translate',
		),
		array(
			'key' => 'field_5ef99d784a139',
			'label' => 'Posts',
			'name' => 'posts',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'collection',
				1 => 'newsexhibitions',
				2 => 'cannabisinfo',
				3 => 'page',
			),
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements' => array(
				0 => 'featured_image',
			),
			'min' => 3,
			'max' => '',
			'return_format' => 'object',
			'translations' => 'sync',
		),
		array(
			'key' => 'field_5ef9be11d6aa8',
			'label' => 'Collection Themes',
			'name' => 'collection_themes',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'collection_themes',
			'field_type' => 'multi_select',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 1,
			'return_format' => 'id',
			'translations' => 'sync',
			'multiple' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/related-posts',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5efa219195264',
	'title' => 'Settings (Catalan)',
	'fields' => array(
		array(
			'key' => 'field_5efa2191b4b78',
			'label' => 'Amsterdam Opening Hours',
			'name' => 'amsterdam_opening_hours_ca',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'br',
			'translations' => 'copy_once',
		),
		array(
			'key' => 'field_5efa2191b4f2c',
			'label' => 'Barcelona Opening Hours',
			'name' => 'Barcelona_opening_hours_ca',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'br',
			'translations' => 'copy_once',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-catalan',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5efa219866e2f',
	'title' => 'Settings (Dutch)',
	'fields' => array(
		array(
			'key' => 'field_5efa21988ff3a',
			'label' => 'Amsterdam Opening Hours',
			'name' => 'amsterdam_opening_hours_nl',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'br',
			'translations' => 'copy_once',
		),
		array(
			'key' => 'field_5efa219890320',
			'label' => 'Barcelona Opening Hours',
			'name' => 'Barcelona_opening_hours_nl',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'br',
			'translations' => 'copy_once',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-dutch',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5efa1c5f813c8',
	'title' => 'Settings (English)',
	'fields' => array(
		array(
			'key' => 'field_5efa1c796afa9',
			'label' => 'Amsterdam Opening Hours',
			'name' => 'amsterdam_opening_hours_en',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'br',
			'translations' => 'copy_once',
		),
		array(
			'key' => 'field_5efa1ca86afaa',
			'label' => 'Barcelona Opening Hours',
			'name' => 'Barcelona_opening_hours_en',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'br',
			'translations' => 'copy_once',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-english',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5efa219f65f48',
	'title' => 'Settings (French)',
	'fields' => array(
		array(
			'key' => 'field_5efa219f875c0',
			'label' => 'Amsterdam Opening Hours',
			'name' => 'amsterdam_opening_hours_fr',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'br',
			'translations' => 'copy_once',
		),
		array(
			'key' => 'field_5efa219f87971',
			'label' => 'Barcelona Opening Hours',
			'name' => 'Barcelona_opening_hours_fr',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'br',
			'translations' => 'copy_once',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-french',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5efa219be134d',
	'title' => 'Settings (German)',
	'fields' => array(
		array(
			'key' => 'field_5efa219c1732b',
			'label' => 'Amsterdam Opening Hours',
			'name' => 'amsterdam_opening_hours_de',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'br',
			'translations' => 'copy_once',
		),
		array(
			'key' => 'field_5efa219c17715',
			'label' => 'Barcelona Opening Hours',
			'name' => 'Barcelona_opening_hours_de',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'br',
			'translations' => 'copy_once',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-german',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5efa204532a93',
	'title' => 'Settings (Non-language Specific)',
	'fields' => array(
		array(
			'key' => 'field_5efa205870087',
			'label' => 'Amount of visitors',
			'name' => 'amount_of_visitors',
			'type' => 'number',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'translations' => 'sync',
		),
		array(
			'key' => 'field_5efa208570088',
			'label' => 'Visitor Count Date',
			'name' => 'visitor_count_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
			'translations' => 'sync',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5efa21952e0ad',
	'title' => 'Settings (Spanish)',
	'fields' => array(
		array(
			'key' => 'field_5efa21954fd53',
			'label' => 'Amsterdam Opening Hours',
			'name' => 'amsterdam_opening_hours_es',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'br',
			'translations' => 'copy_once',
		),
		array(
			'key' => 'field_5efa21955011f',
			'label' => 'Barcelona Opening Hours',
			'name' => 'Barcelona_opening_hours_es',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'br',
			'translations' => 'copy_once',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-spanish',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5ef8a7afdd057',
	'title' => 'Sidebar',
	'fields' => array(
		array(
			'key' => 'field_5ef8a7c31765f',
			'label' => 'Quote Toggle',
			'name' => 'quote_toggle',
			'type' => 'select',
			'instructions' => 'Would you like to add a quote to the sidebar?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'no_quote' => 'No quote',
				'top_quote' => 'Yes, at the top',
				'bottom_quote' => 'Yes, at the bottom',
			),
			'default_value' => 'no_quote',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'translations' => 'sync',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5ef8a87afe09d',
			'label' => 'Quote',
			'name' => 'quote',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5ef8a7c31765f',
						'operator' => '==',
						'value' => 'top_quote',
					),
				),
				array(
					array(
						'field' => 'field_5ef8a7c31765f',
						'operator' => '==',
						'value' => 'bottom_quote',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'translations' => 'translate',
		),
		array(
			'key' => 'field_5ef8a8bcfe09f',
			'label' => 'Quote Author',
			'name' => 'quote_author',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5ef8a7c31765f',
						'operator' => '==',
						'value' => 'top_quote',
					),
				),
				array(
					array(
						'field' => 'field_5ef8a7c31765f',
						'operator' => '==',
						'value' => 'bottom_quote',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'translations' => 'translate',
		),
		array(
			'key' => 'field_5ef8a8cf08459',
			'label' => 'images',
			'name' => 'images',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'insert' => 'append',
			'library' => 'all',
			'min' => 1,
			'max' => 3,
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'translations' => 'sync',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/sidebar',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;